-- ============================================================
-- ADMIN DATABASE LOGIN WITH HASHED PASSWORDS
-- Supabase PostgreSQL + pgcrypto
-- Passwords are NOT stored as plain text.
-- ============================================================

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- 1) Faculty soft-delete columns.
alter table public.ai_faculty_data
  add column if not exists is_deleted boolean not null default false;

alter table public.ai_faculty_data
  add column if not exists deleted_at timestamptz;

-- 2) Admin login table. Store only password_hash.
create table if not exists public.admin_login_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null default 'admin'
    check (role in ('admin', 'super_admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- If an older plain-text password column exists, migrate it to password_hash.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='admin_login_users'
      and column_name='password'
  ) then
    execute $migrate$
      update public.admin_login_users
      set password_hash = extensions.crypt(password, extensions.gen_salt('bf', 10))
      where (password_hash is null or password_hash = '')
        and password is not null
    $migrate$;
  end if;
end $$;

-- 3) Activity log.
create table if not exists public.admin_activity_log_simple (
  id bigint generated by default as identity primary key,
  admin_username text,
  action text not null,
  record_id text,
  details text,
  created_at timestamptz not null default now()
);

-- 4) Protect admin table from direct browser reads/writes.
alter table public.admin_login_users enable row level security;
revoke all on table public.admin_login_users from anon, authenticated;

-- Demo project: faculty data and activity log remain directly accessible.
alter table public.admin_activity_log_simple disable row level security;
alter table public.ai_faculty_data disable row level security;
grant select, insert on table public.admin_activity_log_simple to anon, authenticated;
grant select, insert, update, delete on table public.ai_faculty_data to anon, authenticated;
grant usage, select on sequence public.admin_activity_log_simple_id_seq to anon, authenticated;

-- 5) Verify login. Returns admin details only when username/password match.
create or replace function public.verify_admin_login(
  p_username text,
  p_password text
)
returns table (
  id bigint,
  username text,
  role text,
  is_active boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = public, extensions
as $$
  select a.id, a.username, a.role, a.is_active, a.created_at
  from public.admin_login_users a
  where lower(a.username) = lower(trim(p_username))
    and a.is_active = true
    and a.password_hash = extensions.crypt(p_password, a.password_hash)
  limit 1;
$$;

-- 6) List admin users after re-checking the current admin password.
create or replace function public.list_admin_login_users(
  p_admin_username text,
  p_admin_password text
)
returns table (
  id bigint,
  username text,
  role text,
  is_active boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not exists (
    select 1 from public.admin_login_users a
    where lower(a.username)=lower(trim(p_admin_username))
      and a.is_active=true
      and a.password_hash=extensions.crypt(p_admin_password,a.password_hash)
  ) then
    raise exception 'Invalid administrator credentials';
  end if;

  return query
  select a.id,a.username,a.role,a.is_active,a.created_at
  from public.admin_login_users a
  order by a.created_at desc;
end;
$$;

-- 7) Add an admin. Current admin credentials are verified first.
create or replace function public.add_admin_login_user(
  p_admin_username text,
  p_admin_password text,
  p_username text,
  p_password text,
  p_role text default 'admin'
)
returns table (id bigint, username text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_id bigint;
  v_username text;
begin
  if not exists (
    select 1 from public.admin_login_users a
    where lower(a.username)=lower(trim(p_admin_username))
      and a.is_active=true
      and a.role='super_admin'
      and a.password_hash=extensions.crypt(p_admin_password,a.password_hash)
  ) then
    raise exception 'Super Admin credentials required';
  end if;

  if length(trim(p_username)) < 3 then
    raise exception 'User ID must be at least 3 characters';
  end if;

  if length(p_password) < 8 then
    raise exception 'Password must be at least 8 characters';
  end if;

  if p_role not in ('admin','super_admin') then
    raise exception 'Invalid role';
  end if;

  insert into public.admin_login_users(username,password_hash,role,is_active)
  values (trim(p_username), extensions.crypt(p_password, extensions.gen_salt('bf', 10)), p_role, true)
  returning admin_login_users.id, admin_login_users.username into v_id, v_username;

  return query select v_id, v_username;
end;
$$;

-- 8) Disable/reactivate an admin. Current super-admin credentials are verified.
create or replace function public.set_admin_login_user_active(
  p_admin_username text,
  p_admin_password text,
  p_user_id bigint,
  p_active boolean
)
returns table (username text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_current_id bigint;
  v_username text;
begin
  select a.id into v_current_id
  from public.admin_login_users a
  where lower(a.username)=lower(trim(p_admin_username))
    and a.is_active=true
    and a.role='super_admin'
    and a.password_hash=extensions.crypt(p_admin_password,a.password_hash)
  limit 1;

  if v_current_id is null then
    raise exception 'Super Admin credentials required';
  end if;

  if v_current_id = p_user_id and p_active = false then
    raise exception 'You cannot disable your own account';
  end if;

  update public.admin_login_users
  set is_active=p_active
  where id=p_user_id
  returning admin_login_users.username into v_username;

  if v_username is null then
    raise exception 'Admin user not found';
  end if;

  return query select v_username;
end;
$$;

grant execute on function public.verify_admin_login(text,text) to anon, authenticated;
grant execute on function public.list_admin_login_users(text,text) to anon, authenticated;
grant execute on function public.add_admin_login_user(text,text,text,text,text) to anon, authenticated;
grant execute on function public.set_admin_login_user_active(text,text,bigint,boolean) to anon, authenticated;

-- 9) Create/update first super admin with HASHED password.
insert into public.admin_login_users (username, password_hash, role, is_active)
values ('admin', extensions.crypt('FacultyAI2026', extensions.gen_salt('bf', 10)), 'super_admin', true)
on conflict (username) do update
set password_hash = excluded.password_hash,
    role = excluded.role,
    is_active = true;

-- OPTIONAL: after confirming the new login works, remove the old plain-text password column.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public'
      and table_name='admin_login_users'
      and column_name='password'
  ) then
    execute 'alter table public.admin_login_users drop column password';
  end if;
end $$;

-- First login:
-- User ID: admin
-- Password: FacultyAI2026
-- The database stores only a bcrypt-style hash, not the original password.
